# Generated by Django 2.2.12 on 2021-04-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0005_robot_eqtcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='timecheck',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
