# Generated by Django 2.2.12 on 2021-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0006_robot_timecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='time',
            field=models.BigIntegerField(),
        ),
    ]
