# Generated by Django 2.2.12 on 2021-04-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0007_auto_20210417_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='account_warning_level',
            new_name='ACCOUNT_WARNING_LEVEL',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='balance',
            new_name='BALANCE',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='bear_level',
            new_name='BEAR_LEVEL',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='contract_expired',
            new_name='CONTRACT_EXPIRED',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='currency',
            new_name='CURRENCY',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='eqtcheck',
            new_name='EQTCHECK',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='equity',
            new_name='EQUITY',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='login',
            new_name='LOGIN',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='margin',
            new_name='MARGIN',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='margin_free',
            new_name='MARGIN_FREE',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='margin_level',
            new_name='MARGIN_LEVEL',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='n0_of_loss',
            new_name='N0_OF_LOSS',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='n0_trust_win',
            new_name='N0_TRUST_WIN',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='profit',
            new_name='PROFIT',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='roi_level',
            new_name='ROI_LEVEL',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='run',
            new_name='RUN',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='server',
            new_name='SERVER',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='system_alert',
            new_name='SYSTEM_ALERT',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='time',
            new_name='TIME',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='timecheck',
            new_name='TIMECHECK',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='vps',
            new_name='VPS',
        ),
    ]
