# Generated by Django 2.2.12 on 2021-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0008_auto_20210417_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='ACCOUNT_WARNING_LEVEL',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='BALANCE',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='BEAR_LEVEL',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='CONTRACT_EXPIRED',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='EQUITY',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='LOGIN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='MARGIN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='MARGIN_FREE',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='MARGIN_LEVEL',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='N0_OF_LOSS',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='N0_TRUST_WIN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='PROFIT',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='ROI_LEVEL',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='RUN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='robot',
            name='TIME',
            field=models.CharField(max_length=20),
        ),
    ]
