# Generated by Django 2.2.12 on 2021-04-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0009_auto_20210423_0727'),
        ('fxtecapp', '0009_auto_20210424_0754'),
    ]

    operations = [
    ]
