# Generated by Django 2.2.12 on 2021-04-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0011_auto_20210426_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='N0_TRUST_WIN',
            field=models.TextField(),
        ),
    ]
