# Generated by Django 2.2.12 on 2021-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0012_auto_20210426_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='N0_TRUST_WIN',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='robot',
            name='TIME',
            field=models.FloatField(),
        ),
    ]
