# Generated by Django 2.2.12 on 2021-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=20)),
                ('login', models.IntegerField()),
                ('vps', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('profit', models.FloatField()),
                ('equity', models.FloatField()),
                ('margin', models.FloatField()),
                ('margin_level', models.FloatField()),
                ('margin_free', models.FloatField()),
                ('Run', models.IntegerField()),
                ('bear_level', models.FloatField()),
                ('system_alert', models.BooleanField()),
                ('contract_expried', models.IntegerField()),
                ('roi_level', models.FloatField()),
                ('n0_of_loss', models.IntegerField()),
                ('n0_trust_win', models.FloatField()),
                ('account_warning_level', models.IntegerField()),
            ],
        ),
    ]
