# Generated by Django 3.2 on 2021-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0013_auto_20210426_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='TIME',
            field=models.FloatField(),
        ),
    ]
