# Generated by Django 3.2 on 2021-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0014_alter_robot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='CURRENCY',
            field=models.TextField(),
        ),
    ]
