# Generated by Django 3.2 on 2021-05-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtecapp', '0015_alter_robot_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='TIMECHECK',
            field=models.TextField(default='YES'),
        ),
    ]
